logging:
    level:
        org:
            atmosphere: warn
server:
    port: ${PORT:8080}
vaadin:
    whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
spring:
    jpa:
        defer-datasource-initialization: true
    mustache:
        check-template-location: false
    cloud:
        azure:
            active-directory:
                b2c:
                    enabled: true
                    base-uri: ${AUTHORIZATION_SERVER_BASE_URI}
                    credential:
                        client-id: ${AZURE_CLIENT_ID}
                        client-secret: ${AZURE_CLIENT_SECRET}
                    login-flow: ${LOGIN_USER_FLOW_KEY}               # default to sign-up-or-sign-in, will look up the user-flows map with provided key.
                    logout-success-url: ${LOGOUT_SUCCESS_URL}
                    user-flows:
                        password-reset: ${PASSWORD_RESET_USER_FLOW_NAME}
                        profile-edit: ${PROFILE_EDIT_FLOW_NAME}
                        sign-up-or-sign-in: ${SIGN_UP_OR_SIGN_IN_FLOW_NAME}
            #          user-name-attribute-name: ${USER_NAME_CLAIM}
